#!/usr/bin/with-contenv bash

# Grab latest versions of the app
wget -O /bin/aircast-x86-64 https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/aircast-x86-64 && chmod +x /bin/aircast-x86-64

# Insert runtime commands if users has entered them as environment variables
[ -z "$AIRCAST_VAR" ] || sed -i 's;command=/bin/aircast-x86-64;command=/bin/aircast-x86-64 '"$AIRCAST_VAR"';' /etc/supervisord.conf
